### ISSUE TITLE
feature: Implement Register Page for SecureChat

### ISSUE THREAD

**Issue by ChaithraUmesh21** [Venkatesulu-Basimi/B9IS103-Computer-Systems-Security#5]
Implement a registration page using HTML and Bootstrap for responsive design. Include form fields for username, email, password, and confirm password with validation checks. 

Integrate the frontend with Flask backend (/register endpoint) for user registration logic. Ensure error handling for invalid inputs and provide links for existing users to navigate to the login page.

**Implementation Tasks:**

- Design HTML form for registration page with Bootstrap.
- Add input fields for username, email, password, and confirm password.
- Implement client-side validation using JavaScript.
- Connect the form to Flask backend (/register endpoint).
- Handle registration logic and database integration.
- Display error messages for invalid inputs or registration failures.
- Style the page for a cohesive user experience.
- Provide links for users to navigate to the login page if they already have an account.

 **Expected Outcome:**
- Users will be able to register for SecureChat accounts seamlessly, enhancing user acquisition and engagement. The registration page will ensure a user-friendly experience with intuitive design and robust error handling.

**Comment by Venkatesulu-Basimi** [comment]
Done with changes
